### ISSUE TITLE
No such file or directory: 'mplayer'

### ISSUE THREAD

**Issue by yccphp** [baudm/mplayer.py#23]
`Error`
```
Traceback (most recent call last):
  File "/python/code/play.py", line 13, in <module>
    m = mplayer.Player()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mplayer/core.py", line 109, in __init__
    self.spawn()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mplayer/core.py", line 319, in spawn
    close_fds=(not subprocess._mswindows))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1540, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'mplayer'

```

`code`

```
import mplayer

m = mplayer.Player()
```

Platform: MAC OS
Python Vension: 3.5

Excuse me, hope to get the answer

**Comment by baudm** [comment]
Please check the documentation here:
https://github.com/baudm/mplayer.py/wiki/Player
Particularly the exec_path class attribute

**Comment by shantanudev** [comment]
I am also getting this error. Did you ever find a solution?

**Comment by yccphp** [comment]
yes, install mplayer is ok
