### ISSUE TITLE
Is mplayer.py portable?

### ISSUE THREAD

**Issue by nils-van-zuijlen** [baudm/mplayer.py#25]
Does it work on all systems where [mplayer](//www.mplayerhq.hu/design7/news.html) does?

Personally I had this error when running `p = mplayer.Player()` on ubuntu 16.04 with python 3.5.2.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/mplayer/core.py", line 109, in __init__
    self.spawn()
  File "/usr/local/lib/python3.5/dist-packages/mplayer/core.py", line 319, in spawn
    close_fds=(not subprocess.mswindows))
AttributeError: module 'subprocess' has no attribute 'mswindows'
```

**Comment by baudm** [comment]
This should be fixed in v0.7.1
